workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
    - if: $CI_COMMIT_TAG =~ /v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)-(release|beta|hotfix)(\s*|[1-9]|[1-9][0-9])$/ && $CI_COMMIT_BRANCH =~ "^master$"
      when: always

default:
  tags:
    - runner-docker

variables:
  DOCKER_REPO: harbor.cloudminds.com/gemscloud

stages:
  - builddist
  - buildimage
  - deploydev

builddist:
  stage: builddist
  image: harbor.cloudminds.com/library/node:16.14
  script:
    - export VUE_APP_DATE=`date "+%Y-%m-%d %H:%M:%S"`
    - if [ "$CI_COMMIT_BRANCH" = "develop" ]; then export "VUE_APP_ENVIRONMENT=development"; else export "VUE_APP_ENVIRONMENT=production"; fi
    - echo $VUE_APP_ENVIRONMENT
    - if [ "$CI_COMMIT_BRANCH" = "develop" ]; then export "VUE_APP_RELEASE=develop"; else export "VUE_APP_RELEASE=$CI_COMMIT_TAG"; fi
    - echo $VUE_APP_RELEASE
    - yarn install && yarn build
  cache:
    - key: ${CI_PROJECT_ID}-${CI_COMMIT_REF_SLUG}
      paths:
        - dist
    - key: yarn-cache
      paths:
        - .cache/yarn

buildimage:
  image: harbor.cloudminds.com/library/docker:20.10.10-alpine3.14
  stage: buildimage
  before_script:
    - mkdir -p ~/.docker
    - echo $DOCKER_AUTH_CONFIG > ~/.docker/config.json
  script:
    - docker build -t $DOCKER_REPO/gems-dashboard:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA} .
    - docker push $DOCKER_REPO/gems-dashboard:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
  cache:
    - key: ${CI_PROJECT_ID}-${CI_COMMIT_REF_SLUG}
      paths:
        - dist
    - key: yarn-cache
      paths:
        - .cache/yarn

deploy2dev:
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
  stage: deploydev
  image: harbor.cloudminds.com/library/kubectl:1.20.11-ssh
  script:
    - mkdir -p /root/.ssh && cp ${SSH_KEY_FILE} /root/.ssh/id_rsa && cp ${SSH_PUB_FILE} /root/.ssh/id_rsa.pub && chmod 0600 /root/.ssh/id_rsa && chmod 0644 /root/.ssh/id_rsa.pub
    - ssh -o StrictHostKeyChecking=no 172.16.23.119 -lroot -t -t "cd ~/kubegems && sed -i 's/DASHBOARD_TAG.*/DASHBOARD_TAG=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}/g' .env "
    - ssh -o StrictHostKeyChecking=no 172.16.23.119 -lroot -t -t "cd ~/kubegems && docker-compose up -d"

deploy2pub:
  rules:
    - if: $CI_COMMIT_TAG =~ /v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)-(release|beta|hotfix)(\s*|[1-9]|[1-9][0-9])$/ && $CI_COMMIT_BRANCH =~ "^master$"
  stage: deploydev
  image: harbor.cloudminds.com/library/kubectl:1.20.11
  script:
    - echo "todo deploy pub"
